__name__ = 'qingmi'
__description__ = 'Common modules and toolsets for rapid and efficient development of flask Web.'
__url__ = 'https://github.com/xiongxianzhu/qingmi'
__version_info__ = ('0', '1', '1')
__version__ = '.'.join(__version_info__)
__fullname__ = '-'.join((__name__, __version__))
__author__ = 'zhuxiongxian'
__author_email__ = 'zhuxiongxian@gmail.com'
__maintainer__ = 'zhuxiongxian'
__maintainer_email__ = 'zhuxiongxian@gmail.com'
__license__ = 'BSD'
__copyright__ = '(c) 2018 by zhuxiongxian'
__source__ = 'https://github.com/xiongxianzhu/qingmi'
__keywords__ = 'qingmi flask'